services:
  redis:
    image: redis:latest
    container_name: "aitok_redis"
    environment:
      - REDIS_PASSWORD=password123
    command: ["redis-server", "--requirepass", "password123"]
    ports:
      - "6379:6379"
    volumes:
      - redis_aitok:/data
    restart: unless-stopped

volumes:
  redis_aitok: