jwt:
  secret: bXlTdXBlclNlY3JldEtleU15U3VwZXJTZWNyZXRLZXkzMg==

server:
  port: 18001


spring:
  application:
    name: aitok-member
  config:
    import: "optional:configserver:http://localhost:8001"   # 指向你的 config server
  cloud:
    config:
      username: ${CONFIG_SERVER_USER:admin}                # 从环境变量注入，默认 admin
      password: ${CONFIG_SERVER_PASSWORD:123456789}

  datasource:
    url: jdbc:mysql://localhost:3306/aitok?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      pool-name: HikariPool
      connection-timeout: 30000
      max-lifetime: 60000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: 123456789
      database: 1

  elasticsearch:
    uris:
      - http://localhost:9200
    username: admin1
    password: 123456789
    connection-timeout: 5s
    socket-timeout: 60s

logging:
  file:
    path: ./logs/aitok-member
  level:
    root: info


eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/